# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: sheba

service: auth-lab

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-2
  environment:
    JWT_SECRET: dfaerighaewfwfkwnakjaifhqw
  httpApi:
    cors:
      allowedOrigins:
        - "*"
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - POST
        - DELETE
        - OPTIONS
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:DeleteItem
          Resource: "*"

functions:
  getUsers:
    handler: handler.getUsers
    events:
      - httpApi:
          path: /users
          method: get
  createUser:
    handler: handler.createUser
    events:
      - httpApi:
          path: /users
          method: post
  login:
    handler: handler.login
    events: 
      - httpApi:
          path: /login
          method: post
  registerUser:
    handler: handler.registerUser
    events:
      - httpApi:
          path: /register
          method: post
  getProfile:
    handler: handler.getProfile
    events:
      - httpApi:
          path: /profile
          method: get
  deleteProfile:
    handler: handler.deleteProfile
    events:
      - httpApi:
          path: /profile
          method: delete
